/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <stdio.h>
#include <stdlib.h>
#include "sendreg.h"
#include <rpc/rpc.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

char **send_message_1(char **argp, CLIENT *clnt) {
    static char *clnt_res;

    memset((char *)&clnt_res, 0, sizeof(clnt_res));
    if (clnt_call (clnt, send_message,
        (xdrproc_t) xdr_wrapstring, (caddr_t) argp,
        (xdrproc_t) xdr_wrapstring, (caddr_t) &clnt_res,
        TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}

int main(int argc, char *argv[]) {
    CLIENT *clnt;
    char *server;
    char *message;
    char **result;

    if (argc < 3) {
        fprintf(stderr, "Usage: %s <server_host> <message>\n", argv[0]);
        exit(1);
    }

    server = argv[1];
    message = argv[2];

    /* Create a client handle to connect to the server */
    clnt = clnt_create(server, MESSAGE_PROG, MESSAGE_VERS, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror(server);
        exit(1);
    }

    /* Call the remote procedure */
    result = send_message_1(&message, clnt);
    if (result == NULL) {
        clnt_perror(clnt, server);
        exit(1);
    }

    /* Print the server's response */
    printf("Server response: %s\n", *result);

    /* Clean up */
    clnt_destroy(clnt);
    return 0;
}
